CREATE TABLE post_read_models (
    id BIGINT NOT NULL AUTO_INCREMENT,
    slug VARCHAR(200) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(64) NOT NULL,
    tags_json TEXT NULL,
    post_date DATE NOT NULL,
    post_updated_date DATE NULL,
    thumbnail VARCHAR(512) NULL,
    series VARCHAR(255) NULL,
    featured BIT(1) NOT NULL DEFAULT b'0',
    platform VARCHAR(64) NULL,
    problem_id VARCHAR(128) NULL,
    source_repository VARCHAR(255) NULL,
    source_path VARCHAR(512) NOT NULL,
    source_url VARCHAR(1024) NULL,
    raw_body LONGTEXT NOT NULL,
    commit_hash VARCHAR(64) NULL,
    checksum VARCHAR(128) NOT NULL,
    source_status VARCHAR(32) NOT NULL,
    sync_status VARCHAR(32) NOT NULL,
    visibility VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    synced_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_post_read_models_slug UNIQUE (slug),
    CONSTRAINT uk_post_read_models_source_path UNIQUE (source_path),
    INDEX idx_post_read_models_public (source_status, sync_status, visibility, post_date, slug),
    INDEX idx_post_read_models_category_public (category, source_status, sync_status, visibility, post_date, slug),
    INDEX idx_post_read_models_checksum (checksum)
);
