name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t houkago-server .

      - name: Save Docker Image as tar
        run: docker save -o houkago-server.tar houkago-server

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "houkago-server.tar"
          target: "/home/ubuntu"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into EC2 and Load Docker Image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i /home/ubuntu/houkago-server.tar

            docker stop houkago-server || true
            docker rm houkago-server || true

            docker run -d -p 80:80 --name houkago-server houkago-server
