name: Deploy to EC2 using S3 & CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      zip_file: ${{ steps.set_env.outputs.zip_file }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        id: set_env
        run: echo "zip_file=deploy-${{ github.sha }}.zip" >> $GITHUB_OUTPUT

      - name: Create deployment package (ZIP)
        run: zip -r deploy-${{ github.sha }}.zip appspec.yml start.sh Dockerfile ./

      - name: Upload to S3
        run: aws s3 cp deploy-${{ github.sha }}.zip s3://${{ secrets.AWS_S3_BUCKET }}/

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=${{ needs.build-and-push.outputs.zip_file }},bundleType=zip \
            --region ap-northeast-2

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
